<?php

namespace Bonobo\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM UserBundle:User u WHERE u.id='.$id.''
            )
            ->getResult();
    }
}
